application: squab
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /static
  static_dir: static

- url: /
  script: handlers.main.app

- url: /portada
  script: handlers.portada.app
  login: required

- url: /publicar
  script: handlers.publicar.app
  login: required

- url: /eliminar
  script: handlers.eliminar.app
  login: required

- url: /gustar
  script: handlers.gustar.app
  login: required

- url: /disgustar
  script: handlers.disgustar.app
  login: required

- url: /perfil
  script: handlers.perfil.app
  login: required

- url: /buscar
  script: handlers.buscar.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"